package java.demo.mapper;

import java.demo.model.OrderEntity;
import java.demo.model.OrderEntityExample;
import org.apache.ibatis.annotations.Param;

public interface OrderEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    int deleteByExample(OrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    int insert(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    int insertSelective(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    OrderEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderEntity record, @Param("example") OrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderEntity record, @Param("example") OrderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderEntity record);
}