package java.demo.mapper;

import java.demo.model.PartTimeEntity;
import java.demo.model.PartTimeEntityExample;
import org.apache.ibatis.annotations.Param;

public interface PartTimeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_part_time
     *
     * @mbg.generated
     */
    int deleteByExample(PartTimeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_part_time
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_part_time
     *
     * @mbg.generated
     */
    int insert(PartTimeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_part_time
     *
     * @mbg.generated
     */
    int insertSelective(PartTimeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_part_time
     *
     * @mbg.generated
     */
    PartTimeEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_part_time
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PartTimeEntity record, @Param("example") PartTimeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_part_time
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PartTimeEntity record, @Param("example") PartTimeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_part_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PartTimeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_part_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PartTimeEntity record);
}