package java.demo.model;

import java.util.Date;

public class PartTimeEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_part_time.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_part_time.part__qq
     *
     * @mbg.generated
     */
    private Date partQq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_part_time.submit_state
     *
     * @mbg.generated
     */
    private String submitState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_part_time.part__phone
     *
     * @mbg.generated
     */
    private Date partPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_part_time.part_alipay
     *
     * @mbg.generated
     */
    private String partAlipay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_part_time.part_money
     *
     * @mbg.generated
     */
    private String partMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_part_time.deduct
     *
     * @mbg.generated
     */
    private String deduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_part_time.settle_date
     *
     * @mbg.generated
     */
    private Date settleDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_part_time.part_remark
     *
     * @mbg.generated
     */
    private String partRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_part_time.part_audit
     *
     * @mbg.generated
     */
    private String partAudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_part_time.part_settle_state
     *
     * @mbg.generated
     */
    private String partSettleState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_part_time.finance_remark
     *
     * @mbg.generated
     */
    private String financeRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_part_time.id
     *
     * @return the value of oa_part_time.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_part_time.id
     *
     * @param id the value for oa_part_time.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_part_time.part__qq
     *
     * @return the value of oa_part_time.part__qq
     *
     * @mbg.generated
     */
    public Date getPartQq() {
        return partQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_part_time.part__qq
     *
     * @param partQq the value for oa_part_time.part__qq
     *
     * @mbg.generated
     */
    public void setPartQq(Date partQq) {
        this.partQq = partQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_part_time.submit_state
     *
     * @return the value of oa_part_time.submit_state
     *
     * @mbg.generated
     */
    public String getSubmitState() {
        return submitState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_part_time.submit_state
     *
     * @param submitState the value for oa_part_time.submit_state
     *
     * @mbg.generated
     */
    public void setSubmitState(String submitState) {
        this.submitState = submitState == null ? null : submitState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_part_time.part__phone
     *
     * @return the value of oa_part_time.part__phone
     *
     * @mbg.generated
     */
    public Date getPartPhone() {
        return partPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_part_time.part__phone
     *
     * @param partPhone the value for oa_part_time.part__phone
     *
     * @mbg.generated
     */
    public void setPartPhone(Date partPhone) {
        this.partPhone = partPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_part_time.part_alipay
     *
     * @return the value of oa_part_time.part_alipay
     *
     * @mbg.generated
     */
    public String getPartAlipay() {
        return partAlipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_part_time.part_alipay
     *
     * @param partAlipay the value for oa_part_time.part_alipay
     *
     * @mbg.generated
     */
    public void setPartAlipay(String partAlipay) {
        this.partAlipay = partAlipay == null ? null : partAlipay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_part_time.part_money
     *
     * @return the value of oa_part_time.part_money
     *
     * @mbg.generated
     */
    public String getPartMoney() {
        return partMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_part_time.part_money
     *
     * @param partMoney the value for oa_part_time.part_money
     *
     * @mbg.generated
     */
    public void setPartMoney(String partMoney) {
        this.partMoney = partMoney == null ? null : partMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_part_time.deduct
     *
     * @return the value of oa_part_time.deduct
     *
     * @mbg.generated
     */
    public String getDeduct() {
        return deduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_part_time.deduct
     *
     * @param deduct the value for oa_part_time.deduct
     *
     * @mbg.generated
     */
    public void setDeduct(String deduct) {
        this.deduct = deduct == null ? null : deduct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_part_time.settle_date
     *
     * @return the value of oa_part_time.settle_date
     *
     * @mbg.generated
     */
    public Date getSettleDate() {
        return settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_part_time.settle_date
     *
     * @param settleDate the value for oa_part_time.settle_date
     *
     * @mbg.generated
     */
    public void setSettleDate(Date settleDate) {
        this.settleDate = settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_part_time.part_remark
     *
     * @return the value of oa_part_time.part_remark
     *
     * @mbg.generated
     */
    public String getPartRemark() {
        return partRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_part_time.part_remark
     *
     * @param partRemark the value for oa_part_time.part_remark
     *
     * @mbg.generated
     */
    public void setPartRemark(String partRemark) {
        this.partRemark = partRemark == null ? null : partRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_part_time.part_audit
     *
     * @return the value of oa_part_time.part_audit
     *
     * @mbg.generated
     */
    public String getPartAudit() {
        return partAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_part_time.part_audit
     *
     * @param partAudit the value for oa_part_time.part_audit
     *
     * @mbg.generated
     */
    public void setPartAudit(String partAudit) {
        this.partAudit = partAudit == null ? null : partAudit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_part_time.part_settle_state
     *
     * @return the value of oa_part_time.part_settle_state
     *
     * @mbg.generated
     */
    public String getPartSettleState() {
        return partSettleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_part_time.part_settle_state
     *
     * @param partSettleState the value for oa_part_time.part_settle_state
     *
     * @mbg.generated
     */
    public void setPartSettleState(String partSettleState) {
        this.partSettleState = partSettleState == null ? null : partSettleState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_part_time.finance_remark
     *
     * @return the value of oa_part_time.finance_remark
     *
     * @mbg.generated
     */
    public String getFinanceRemark() {
        return financeRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_part_time.finance_remark
     *
     * @param financeRemark the value for oa_part_time.finance_remark
     *
     * @mbg.generated
     */
    public void setFinanceRemark(String financeRemark) {
        this.financeRemark = financeRemark == null ? null : financeRemark.trim();
    }
}