package demo.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class WorkPayEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_work.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_work.pay_date
     *
     * @mbg.generated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd")
    private Date payDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_work.pay_user
     *
     * @mbg.generated
     */
    private String payUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_work.pay_project
     *
     * @mbg.generated
     */
    private String payProject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_work.pay_money
     *
     * @mbg.generated
     */
    private String payMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_work.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_work.get_user
     *
     * @mbg.generated
     */
    private String getUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_work.audit
     *
     * @mbg.generated
     */
    private String audit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_work.settle
     *
     * @mbg.generated
     */
    private String settle;

    private String partName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_work.id
     *
     * @return the value of oa_work.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_work.id
     *
     * @param id the value for oa_work.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_work.pay_date
     *
     * @return the value of oa_work.pay_date
     *
     * @mbg.generated
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_work.pay_date
     *
     * @param payDate the value for oa_work.pay_date
     *
     * @mbg.generated
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_work.pay_user
     *
     * @return the value of oa_work.pay_user
     *
     * @mbg.generated
     */
    public String getPayUser() {
        return payUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_work.pay_user
     *
     * @param payUser the value for oa_work.pay_user
     *
     * @mbg.generated
     */
    public void setPayUser(String payUser) {
        this.payUser = payUser == null ? null : payUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_work.pay_project
     *
     * @return the value of oa_work.pay_project
     *
     * @mbg.generated
     */
    public String getPayProject() {
        return payProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_work.pay_project
     *
     * @param payProject the value for oa_work.pay_project
     *
     * @mbg.generated
     */
    public void setPayProject(String payProject) {
        this.payProject = payProject == null ? null : payProject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_work.pay_money
     *
     * @return the value of oa_work.pay_money
     *
     * @mbg.generated
     */
    public String getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_work.pay_money
     *
     * @param payMoney the value for oa_work.pay_money
     *
     * @mbg.generated
     */
    public void setPayMoney(String payMoney) {
        this.payMoney = payMoney == null ? null : payMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_work.remark
     *
     * @return the value of oa_work.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_work.remark
     *
     * @param remark the value for oa_work.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_work.get_user
     *
     * @return the value of oa_work.get_user
     *
     * @mbg.generated
     */
    public String getGetUser() {
        return getUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_work.get_user
     *
     * @param getUser the value for oa_work.get_user
     *
     * @mbg.generated
     */
    public void setGetUser(String getUser) {
        this.getUser = getUser == null ? null : getUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_work.audit
     *
     * @return the value of oa_work.audit
     *
     * @mbg.generated
     */
    public String getAudit() {
        return audit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_work.audit
     *
     * @param audit the value for oa_work.audit
     *
     * @mbg.generated
     */
    public void setAudit(String audit) {
        this.audit = audit == null ? null : audit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_work.settle
     *
     * @return the value of oa_work.settle
     *
     * @mbg.generated
     */
    public String getSettle() {
        return settle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_work.settle
     *
     * @param settle the value for oa_work.settle
     *
     * @mbg.generated
     */
    public void setSettle(String settle) {
        this.settle = settle == null ? null : settle.trim();
    }

    public String getPartName() {
        return partName;
    }

    public void setPartName(String partName) {
        this.partName = partName;
    }
}