package demo.mapper;


import demo.model.dto.*;
import demo.model.OrderEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    int insert(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    int insertSelective(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    OrderEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderEntity record);

    List<PartTimeOrderRes> selectAllOrder(OrderReqVo vo);

    int auditOrder(AuditVo vo);

    OrderEntity selectByOrderNumber(@Param("orderNumber") String orderNumber);

    int deleteByPrimaryKeys(@Param("ids") Long[] ids);

    List<ServiceVo> selectAllService(@Param("serviceName") String serviceName, @Param("partName") String partName);

    List<ServiceVo> selectAllSendService(@Param("serviceName") String serviceName, @Param("partName") String partName);

    List<OrderCountVo> countOrder(@Param("ids") Long[] ids);
}