package demo.mapper;

import demo.model.SysUserroleEntity;

import java.util.List;

public interface SysUserroleEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated
     */
    int insert(SysUserroleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbggenerated
     */
    int insertSelective(SysUserroleEntity record);

    List<SysUserroleEntity> queryUserroleByuserid(Long userid);
}