package demo.mapper;

import demo.model.dto.AuditVo;
import demo.model.dto.WorkPayReqVo;
import demo.model.WorkPayEntity;

import java.util.List;

public interface WorkPayEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_work
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_work
     *
     * @mbg.generated
     */
    int insert(WorkPayEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_work
     *
     * @mbg.generated
     */
    int insertSelective(WorkPayEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_work
     *
     * @mbg.generated
     */
    WorkPayEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_work
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WorkPayEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_work
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WorkPayEntity record);

    List<WorkPayEntity> selectAllOrder(WorkPayReqVo vo);

    int auditOrder(AuditVo vo);
}